import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Posts } from "@/pages/components/Posts";
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export const Home = () => {
  return (
    <>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2 className={inter.className}>
          Posts
        </h2>
        <Posts />
      </main>
    </>
  )
}

export default Home;